name: dev-prod-run

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      
jobs:
  train-experiment:
    name: train experiment
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_dev.yml -g end_to_end_demo -w ee-demo -s
  train-prod:
    name: train production
    runs-on: ubuntu-latest
    environment: PROD
    needs: job1
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_prod.yml -g end_to_end_demo -w ee-demo -s