name: Placeholder WF, runs on PR Open

on:
  pull_request:
    types:
      - opened

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"